=== Armatiek/xmlindex/home/conf/xsd/index-configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xs:element name="index-configuration">
    <xs:complexType>
      <xs:all>
        <xs:element name="typed-value-config" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="typed-value-def" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:all>
                    <xs:element name="node-type" type="node-type"/>
                    <xs:element name="node-name" type="xs:QName"/>
                    <xs:element name="item-type" type="item-type"/>
                  </xs:all>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="virtual-attribute-config" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="virtual-attribute-def" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:all>
                    <xs:element name="bindings">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="document-element" minOccurs="0"/>
                          <xs:element name="element-name" type="xs:QName" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="virtual-attribute-name" type="xs:string"/>
                    <xs:element name="function-name" type="xs:QName"/>
                    <xs:element name="item-type" type="item-type"/>
                    <xs:element name="store-value" type="xs:boolean" minOccurs="0" default="false"/>
                    <xs:element name="index-analyzer" type="analyzer-type" minOccurs="0"/>
                    <xs:element name="query-analyzer" type="analyzer-type" minOccurs="0"/>
                  </xs:all>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="pluggable-index-config" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="pluggable-index-def" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="class-name" type="xs:string"/>
                    <xs:element name="param" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:attribute name="name" type="xs:string" use="required"/>
                        <xs:attribute name="value" type="xs:string" use="required"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="pluggable-file-convertor-config" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="pluggable-file-convertor-def" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="class-name" type="xs:string"/>
                    <xs:element name="param" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:attribute name="name" type="xs:string" use="required"/>
                        <xs:attribute name="value" type="xs:string" use="required"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:all>
    </xs:complexType>
  </xs:element>

  <xs:simpleType name="node-type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="element()"/>
      <xs:enumeration value="attribute()"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="item-type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="xs:string"/>
      <xs:enumeration value="xs:boolean"/>
      <xs:enumeration value="xs:float"/>
      <xs:enumeration value="xs:double"/>
      <xs:enumeration value="xs:long"/>
      <xs:enumeration value="xs:int"/>
      <xs:enumeration value="xs:short"/>
      <xs:enumeration value="xs:byte"/>
      <xs:enumeration value="xs:dateTime"/>
      <xs:enumeration value="xs:date"/>
      <xs:enumeration value="xs:time"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="analyzer-type">
    <xs:choice>
      <xs:element name="class-analyzer" type="xs:string"/>
      <xs:element name="analyzer">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="char-filter" type="filter-type" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="tokenizer" type="filter-type"/>
            <xs:element name="filter" type="filter-type" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="filter-type">
    <xs:attribute name="class" type="xs:string" use="required"/>
    <xs:anyAttribute namespace="##local" processContents="lax"/>
  </xs:complexType>

</xs:schema>

=== Armatiek/xmlindex/home/indexes/index-bwb/conf/index-configuration.xml
<?xml version="1.0"?>
<index-configuration 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xmlns:va="http://www.armatiek.nl/xmlindex/virtualattribute"
  xsi:noNamespaceSchemaLocation="../../../conf/xsd/index-configuration.xsd">
  
  <typed-value-config>
    <typed-value-def>
      <node-type>attribute()</node-type>
      <node-name>inwerking</node-name>
      <item-type>xs:date</item-type>
    </typed-value-def>
  </typed-value-config>
  
  <virtual-attribute-config>
    <virtual-attribute-def>
      <bindings>
        <element-name>expression</element-name>  
      </bindings>
      <virtual-attribute-name>bwb-id</virtual-attribute-name>
      <function-name>va:expression-bwb-id</function-name>
      <item-type>xs:string</item-type>
    </virtual-attribute-def>
    <virtual-attribute-def>
      <bindings>
        <element-name>expression</element-name>  
      </bindings>
      <virtual-attribute-name>inwerkingtredingsdatum</virtual-attribute-name>
      <function-name>va:expression-inwerkingtredingsdatum</function-name>
      <item-type>xs:date</item-type>
    </virtual-attribute-def>
    <virtual-attribute-def>
      <bindings>
        <element-name>expression</element-name>  
      </bindings>
      <virtual-attribute-name>einddatum</virtual-attribute-name>
      <function-name>va:expression-einddatum</function-name>
      <item-type>xs:date</item-type>
    </virtual-attribute-def>
    <virtual-attribute-def>
      <bindings>
        <element-name>expression</element-name>  
      </bindings>
      <virtual-attribute-name>zichtdatum-start</virtual-attribute-name>
      <function-name>va:expression-zichtdatum-start</function-name>
      <item-type>xs:date</item-type>
    </virtual-attribute-def>
    <virtual-attribute-def>
      <bindings>
        <element-name>expression</element-name>  
      </bindings>
      <virtual-attribute-name>zichtdatum-eind</virtual-attribute-name>
      <function-name>va:expression-zichtdatum-eind</function-name>
      <item-type>xs:date</item-type>
    </virtual-attribute-def>
    <virtual-attribute-def>
      <bindings>
        <element-name>toestand</element-name>  
      </bindings>
      <virtual-attribute-name>expression-id</virtual-attribute-name>
      <function-name>va:toestand-expression-id</function-name>
      <item-type>xs:string</item-type>
    </virtual-attribute-def>
    <virtual-attribute-def>
      <bindings>
        <element-name>toestand</element-name>  
      </bindings>
      <virtual-attribute-name>citeertitel</virtual-attribute-name>
      <function-name>va:citeertitel</function-name>
      <item-type>xs:string</item-type>
      <index-analyzer>
        <analyzer>
          <tokenizer class="standard"/>
          <filter class="standard"/>
          <filter class="lowercase"/>
          <filter class="stop" ignoreCase="true"/>
        </analyzer>
      </index-analyzer>
      <query-analyzer>
        <analyzer>
          <tokenizer class="standard"/>
          <filter class="standard"/>
          <filter class="lowercase"/>
          <filter class="stop" ignoreCase="true"/>
        </analyzer>
      </query-analyzer>
      <!--
      <index-analyzer>
        <analyzer class="org.apache.lucene.analysis.standard.StandardAnalyzer"/>
      </index-analyzer>
      <query-analyzer>
        <analyzer class="org.apache.lucene.analysis.standard.StandardAnalyzer"/>
      </query-analyzer>
      -->
    </virtual-attribute-def>
  </virtual-attribute-config>
  
  <pluggable-index-config/>
    
</index-configuration>
